"""Constants for the Anima Artist Mixer nodes."""

FUSION_INTERPOLATE = "interpolate"
FUSION_CONCAT_WITH_BASE = "concat_with_base"
FUSION_BASE_PRESERVE = "base_preserve"

COMBINE_CONCAT = "concat"
COMBINE_OUTPUT_AVG = "output_avg"
COMBINE_LOWRANK_AVG = "lowrank_avg"

MAX_ARTISTS = 32

STATIC_CAPTURE_K_DEFAULT = 6
STATIC_CAPTURE_K_MAX = 12

ANCHOR_SEEDS_POOL = [42, 100, 200, 300]
ANCHOR_SEEDS_MAX = len(ANCHOR_SEEDS_POOL)
ANCHOR_LAYER_THRESHOLD_DISABLED = -1

WEIGHT_MIN = 0.0
WEIGHT_MAX = 4.0
